# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import vegvisirCommon_pb2 as vegvisirCommon__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='frontier.proto',
  package='vegvisir.protocol.datatype',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66rontier.proto\x12\x1avegvisir.protocol.datatype\x1a\x14vegvisirCommon.proto\"\x19\n\x07HashSet\x12\x0e\n\x06hashes\x18\x01 \x03(\x0c\"\xa6\x02\n\x07Request\x12\x36\n\x04type\x18\x01 \x01(\x0e\x32(.vegvisir.protocol.datatype.Request.Type\x12\x33\n\x04send\x18\x02 \x01(\x0b\x32#.vegvisir.protocol.datatype.HashSetH\x00\x12\x32\n\x03\x61\x64\x64\x18\x03 \x01(\x0b\x32#.vegvisir.common.datatype.AddBlocksH\x00\"j\n\x04Type\x12\x11\n\rDUMMY_REQUEST\x10\x00\x12\x15\n\x11SEND_FRONTIER_SET\x10\x01\x12\x0e\n\nSEND_BLOCK\x10\x02\x12\r\n\tADD_BLOCK\x10\x03\x12\x19\n\x15RECONCILIATION_NEEDED\x10\x04\x42\x0e\n\x0ctargets_type\"\xaa\x01\n\x08Response\x12;\n\x0chashResponse\x18\x01 \x01(\x0b\x32#.vegvisir.protocol.datatype.HashSetH\x00\x12<\n\rblockResponse\x18\x02 \x01(\x0b\x32#.vegvisir.common.datatype.AddBlocksH\x00\x12\x11\n\tis_subset\x18\x03 \x01(\x08\x42\x10\n\x0eresponse_types\"\x9c\x01\n\x0f\x46rontierMessage\x12\x36\n\x07request\x18\x01 \x01(\x0b\x32#.vegvisir.protocol.datatype.RequestH\x00\x12\x38\n\x08response\x18\x02 \x01(\x0b\x32$.vegvisir.protocol.datatype.ResponseH\x00\x42\x17\n\x15\x66rontier_message_typeb\x06proto3')
  ,
  dependencies=[vegvisirCommon__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='vegvisir.protocol.datatype.Request.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY_REQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_FRONTIER_SET', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEND_BLOCK', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_BLOCK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECONCILIATION_NEEDED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=268,
  serialized_end=374,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_TYPE)


_HASHSET = _descriptor.Descriptor(
  name='HashSet',
  full_name='vegvisir.protocol.datatype.HashSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashes', full_name='vegvisir.protocol.datatype.HashSet.hashes', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=93,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='vegvisir.protocol.datatype.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='vegvisir.protocol.datatype.Request.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='send', full_name='vegvisir.protocol.datatype.Request.send', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='add', full_name='vegvisir.protocol.datatype.Request.add', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='targets_type', full_name='vegvisir.protocol.datatype.Request.targets_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=96,
  serialized_end=390,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='vegvisir.protocol.datatype.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hashResponse', full_name='vegvisir.protocol.datatype.Response.hashResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blockResponse', full_name='vegvisir.protocol.datatype.Response.blockResponse', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_subset', full_name='vegvisir.protocol.datatype.Response.is_subset', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response_types', full_name='vegvisir.protocol.datatype.Response.response_types',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=393,
  serialized_end=563,
)


_FRONTIERMESSAGE = _descriptor.Descriptor(
  name='FrontierMessage',
  full_name='vegvisir.protocol.datatype.FrontierMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='vegvisir.protocol.datatype.FrontierMessage.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='vegvisir.protocol.datatype.FrontierMessage.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='frontier_message_type', full_name='vegvisir.protocol.datatype.FrontierMessage.frontier_message_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=566,
  serialized_end=722,
)

_REQUEST.fields_by_name['type'].enum_type = _REQUEST_TYPE
_REQUEST.fields_by_name['send'].message_type = _HASHSET
_REQUEST.fields_by_name['add'].message_type = vegvisirCommon__pb2._ADDBLOCKS
_REQUEST_TYPE.containing_type = _REQUEST
_REQUEST.oneofs_by_name['targets_type'].fields.append(
  _REQUEST.fields_by_name['send'])
_REQUEST.fields_by_name['send'].containing_oneof = _REQUEST.oneofs_by_name['targets_type']
_REQUEST.oneofs_by_name['targets_type'].fields.append(
  _REQUEST.fields_by_name['add'])
_REQUEST.fields_by_name['add'].containing_oneof = _REQUEST.oneofs_by_name['targets_type']
_RESPONSE.fields_by_name['hashResponse'].message_type = _HASHSET
_RESPONSE.fields_by_name['blockResponse'].message_type = vegvisirCommon__pb2._ADDBLOCKS
_RESPONSE.oneofs_by_name['response_types'].fields.append(
  _RESPONSE.fields_by_name['hashResponse'])
_RESPONSE.fields_by_name['hashResponse'].containing_oneof = _RESPONSE.oneofs_by_name['response_types']
_RESPONSE.oneofs_by_name['response_types'].fields.append(
  _RESPONSE.fields_by_name['blockResponse'])
_RESPONSE.fields_by_name['blockResponse'].containing_oneof = _RESPONSE.oneofs_by_name['response_types']
_FRONTIERMESSAGE.fields_by_name['request'].message_type = _REQUEST
_FRONTIERMESSAGE.fields_by_name['response'].message_type = _RESPONSE
_FRONTIERMESSAGE.oneofs_by_name['frontier_message_type'].fields.append(
  _FRONTIERMESSAGE.fields_by_name['request'])
_FRONTIERMESSAGE.fields_by_name['request'].containing_oneof = _FRONTIERMESSAGE.oneofs_by_name['frontier_message_type']
_FRONTIERMESSAGE.oneofs_by_name['frontier_message_type'].fields.append(
  _FRONTIERMESSAGE.fields_by_name['response'])
_FRONTIERMESSAGE.fields_by_name['response'].containing_oneof = _FRONTIERMESSAGE.oneofs_by_name['frontier_message_type']
DESCRIPTOR.message_types_by_name['HashSet'] = _HASHSET
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['FrontierMessage'] = _FRONTIERMESSAGE

HashSet = _reflection.GeneratedProtocolMessageType('HashSet', (_message.Message,), dict(
  DESCRIPTOR = _HASHSET,
  __module__ = 'frontier_pb2'
  # @@protoc_insertion_point(class_scope:vegvisir.protocol.datatype.HashSet)
  ))
_sym_db.RegisterMessage(HashSet)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'frontier_pb2'
  # @@protoc_insertion_point(class_scope:vegvisir.protocol.datatype.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'frontier_pb2'
  # @@protoc_insertion_point(class_scope:vegvisir.protocol.datatype.Response)
  ))
_sym_db.RegisterMessage(Response)

FrontierMessage = _reflection.GeneratedProtocolMessageType('FrontierMessage', (_message.Message,), dict(
  DESCRIPTOR = _FRONTIERMESSAGE,
  __module__ = 'frontier_pb2'
  # @@protoc_insertion_point(class_scope:vegvisir.protocol.datatype.FrontierMessage)
  ))
_sym_db.RegisterMessage(FrontierMessage)


# @@protoc_insertion_point(module_scope)
