# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='generic.proto',
  package='vegvisir.protocol.datatype',
  syntax='proto3',
  serialized_pb=_b('\n\rgeneric.proto\x12\x1avegvisir.protocol.datatype\"5\n\x0eGenericMessage\x12\x12\n\nidentifier\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENERICMESSAGE = _descriptor.Descriptor(
  name='GenericMessage',
  full_name='vegvisir.protocol.datatype.GenericMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='vegvisir.protocol.datatype.GenericMessage.identifier', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='vegvisir.protocol.datatype.GenericMessage.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['GenericMessage'] = _GENERICMESSAGE

GenericMessage = _reflection.GeneratedProtocolMessageType('GenericMessage', (_message.Message,), dict(
  DESCRIPTOR = _GENERICMESSAGE,
  __module__ = 'generic_pb2'
  # @@protoc_insertion_point(class_scope:vegvisir.protocol.datatype.GenericMessage)
  ))
_sym_db.RegisterMessage(GenericMessage)


# @@protoc_insertion_point(module_scope)
