# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vegvisirCommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import charlotte_pb2 as charlotte__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vegvisirCommon.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x14vegvisirCommon.proto\x1a\x0f\x63harlotte.proto\"2\n\tAddBlocks\x12%\n\x0b\x62locksToAdd\x18\x01 \x03(\x0b\x32\x10.charlotte.BlockBN\n\"com.vegvisir.common.datatype.protoB\x1bVegvisirCommonDatatypeProtoP\x01\xa2\x02\x08VEGVISIRb\x06proto3')
  ,
  dependencies=[charlotte__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDBLOCKS = _descriptor.Descriptor(
  name='AddBlocks',
  full_name='AddBlocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocksToAdd', full_name='AddBlocks.blocksToAdd', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=91,
)

_ADDBLOCKS.fields_by_name['blocksToAdd'].message_type = charlotte__pb2._BLOCK
DESCRIPTOR.message_types_by_name['AddBlocks'] = _ADDBLOCKS

AddBlocks = _reflection.GeneratedProtocolMessageType('AddBlocks', (_message.Message,), dict(
  DESCRIPTOR = _ADDBLOCKS,
  __module__ = 'vegvisirCommon_pb2'
  # @@protoc_insertion_point(class_scope:AddBlocks)
  ))
_sym_db.RegisterMessage(AddBlocks)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"com.vegvisir.common.datatype.protoB\033VegvisirCommonDatatypeProtoP\001\242\002\010VEGVISIR'))
# @@protoc_insertion_point(module_scope)
