# Generated by Django 2.2.2 on 2019-07-17 17:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.AddField(
            model_name='transaction',
            name='dependencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='isOn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payload',
            field=models.CharField(max_length=100),
        ),
    ]
